### ISSUE TITLE
Add maven wrapper

### ISSUE THREAD

**Issue by camaral** [sonatype-nexus-community/nexus-repository-puppet#15]
Adding maven wrapper to the project makes it easier to start and keep everybody on the same maven version. Maven is pretty stable and does not break often, but it still good to keep everyone in the same page.

* **What are you trying to do?**
Add mvnw to the project

* **What feature or behavior is this required for?**
It makes easier to keep compatibility between the developers.

* **How could we solve this issue? (Not knowing is okay!)**
Run `mvn -N io.takari:maven:wrapper` and commit the files.

* **Anything else?**
Let me know if this suggestion is something that you guys would like to have. If so, I can submit a Pull Request.

**Comment by DarthHater** [comment]
We might not actually need this soon!

We are working on publishing these plugins to Maven Central, which would make building it only necessary for people who want to tinker on it. That said, using the wrapper could be neat for even that case, but I imagine most Java people will have maven?

**Comment by camaral** [comment]
Hi @DarthHater,
thank you for replying and thank you for writing this plugin, it is helping me a lot.
I agree with you, most Java people work directly with a local Maven installation.
I added `mvnw` to my fork though, because it works better on my workstation.
Feel free to close this issue and reject the pull request.
